spring.application.name=leadera
spring.datasource.url=jdbc:mysql://localhost:3306/leadera
spring.datasource.username=root
spring.datasource.password=Matecamilion2005

spring.jpa.hibernate.ddl-auto=update